[versions]
agp = "8.7.0"
exp4j = "0.4.8"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"

[libraries]
exp4j = { module = "net.objecthunter:exp4j", version.ref = "exp4j" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

